# Identificação de Variáveis Preditoras
______

CMSP-> Utils -> data_science -> Exploracao -> Identificacao -> exemplos_ident_var_preditoras

## Configurações necessárias para rodar as funções

In [0]:
%run
/Utils/configuration

## Carregar os dados e transformar
* vamos carregar aqui, o dataset para análise junto com o dicionário de dados.

In [0]:
dados = spark.sql(''' SELECT * FROM datascience.application_train_csv ''')

In [0]:
df = spark.sql('''SELECT * FROM datascience.homecredit_columns_description__csv WHERE Table = 'application_{train|test}.csv' ''')
df = df.withColumnRenamed('Row', 'feature')

#### Tratamento e análise do dicionário

In [0]:
df = df.toPandas()

In [0]:
# extrair as variáveis e classificá-las em pequenos grupos
features = list(df['feature'])
df['group'] = df['feature'].map({'SK_ID_CURR': 0, 'TARGET': 0, 'NAME_CONTRACT_TYPE': 4, 'CODE_GENDER': 2, 'FLAG_OWN_CAR': 3, 'FLAG_OWN_REALTY': 3, 'CNT_CHILDREN': 2, 'AMT_INCOME_TOTAL': 4, 'AMT_CREDIT': 4, 'AMT_ANNUITY': 4, 'AMT_GOODS_PRICE': 4, 'NAME_TYPE_SUITE': 15, 'NAME_INCOME_TYPE': 15, 'NAME_EDUCATION_TYPE': 15, 'NAME_FAMILY_STATUS': 15, 'NAME_HOUSING_TYPE': 15, 'REGION_POPULATION_RELATIVE': 15, 'DAYS_BIRTH': 2, 'DAYS_EMPLOYED': 5, 'DAYS_REGISTRATION': 10, 'DAYS_ID_PUBLISH': 10, 'OWN_CAR_AGE': 3, 'FLAG_MOBIL': 11, 'FLAG_EMP_PHONE': 11, 'FLAG_WORK_PHONE': 11, 'FLAG_CONT_MOBILE': 11, 'FLAG_PHONE': 11, 'FLAG_EMAIL': 11, 'OCCUPATION_TYPE': 5, 'CNT_FAM_MEMBERS': 2, 'REGION_RATING_CLIENT': 5, 'REGION_RATING_CLIENT_W_CITY': 5, 'WEEKDAY_APPR_PROCESS_START': 12, 'HOUR_APPR_PROCESS_START': 12,'REG_REGION_NOT_LIVE_REGION': 13, 'REG_REGION_NOT_WORK_REGION': 13, 'LIVE_REGION_NOT_WORK_REGION': 13, 'REG_CITY_NOT_LIVE_CITY':13, 'REG_CITY_NOT_WORK_CITY':13, 'LIVE_CITY_NOT_WORK_CITY': 13, 'ORGANIZATION_TYPE': 5, 'EXT_SOURCE_1': 14, 'EXT_SOURCE_2': 14, 'EXT_SOURCE_3': 14, 'APARTMENTS_AVG': 16, 'BASEMENTAREA_AVG': 17, 'YEARS_BEGINEXPLUATATION_AVG': 18, 'YEARS_BUILD_AVG': 19, 'COMMONAREA_AVG': 20, 'ELEVATORS_AVG': 21, 'ENTRANCES_AVG': 22, 'FLOORSMAX_AVG': 23, 'FLOORSMIN_AVG': 23, 'LANDAREA_AVG': 25, 'LIVINGAPARTMENTS_AVG': 27, 'LIVINGAREA_AVG': 27, 'NONLIVINGAPARTMENTS_AVG': 28, 'NONLIVINGAREA_AVG': 28, 'APARTMENTS_MODE': 16, 'BASEMENTAREA_MODE': 17, 'YEARS_BEGINEXPLUATATION_MODE': 18, 'YEARS_BUILD_MODE': 19, 'COMMONAREA_MODE': 20, 'ELEVATORS_MODE': 21, 'ENTRANCES_MODE': 22, 'FLOORSMAX_MODE': 23, 'FLOORSMIN_MODE': 23, 'LANDAREA_MODE': 25, 'LIVINGAPARTMENTS_MODE': 27, 'LIVINGAREA_MODE': 27, 'NONLIVINGAPARTMENTS_MODE': 28, 'NONLIVINGAREA_MODE': 28, 'APARTMENTS_MEDI': 16, 'BASEMENTAREA_MEDI': 17, 'YEARS_BEGINEXPLUATATION_MEDI': 18, 'YEARS_BUILD_MEDI': 19, 'COMMONAREA_MEDI': 20, 'ELEVATORS_MEDI': 21, 'ENTRANCES_MEDI': 22, 'FLOORSMAX_MEDI': 23, 'FLOORSMIN_MEDI': 23, 'LANDAREA_MEDI': 25, 'LIVINGAPARTMENTS_MEDI': 27, 'LIVINGAREA_MEDI': 27, 'NONLIVINGAPARTMENTS_MEDI': 28, 'NONLIVINGAREA_MEDI': 28, 'FONDKAPREMONT_MODE': 30, 'HOUSETYPE_MODE': 30, 'TOTALAREA_MODE': 30, 'WALLSMATERIAL_MODE': 30, 'EMERGENCYSTATE_MODE': 30, 'OBS_30_CNT_SOCIAL_CIRCLE': 7, 'DEF_30_CNT_SOCIAL_CIRCLE': 7, 'OBS_60_CNT_SOCIAL_CIRCLE': 7, 'DEF_60_CNT_SOCIAL_CIRCLE': 7, 'DAYS_LAST_PHONE_CHANGE': 10, 'FLAG_DOCUMENT_2': 8, 'FLAG_DOCUMENT_3': 8, 'FLAG_DOCUMENT_4': 8, 'FLAG_DOCUMENT_5': 8, 'FLAG_DOCUMENT_6': 8, 'FLAG_DOCUMENT_7': 8, 'FLAG_DOCUMENT_8': 8, 'FLAG_DOCUMENT_9': 8, 'FLAG_DOCUMENT_10': 8, 'FLAG_DOCUMENT_11': 8, 'FLAG_DOCUMENT_12': 8, 'FLAG_DOCUMENT_13': 8, 'FLAG_DOCUMENT_14': 8, 'FLAG_DOCUMENT_15': 8, 'FLAG_DOCUMENT_16': 8, 'FLAG_DOCUMENT_17': 8, 'FLAG_DOCUMENT_18': 8, 'FLAG_DOCUMENT_19': 8, 'FLAG_DOCUMENT_20': 8, 'FLAG_DOCUMENT_21': 8, 'AMT_REQ_CREDIT_BUREAU_HOUR': 9, 'AMT_REQ_CREDIT_BUREAU_DAY': 9, 'AMT_REQ_CREDIT_BUREAU_WEEK': 9, 'AMT_REQ_CREDIT_BUREAU_MON': 9, 'AMT_REQ_CREDIT_BUREAU_QRT': 9, 'AMT_REQ_CREDIT_BUREAU_YEAR': 9})

In [0]:
# dicionario das flags dos grupos tipados, passando coluna tipo de grupo para categoria e contando os tipos de variáveis.
df['tipo_grupo'] = df['group'].map({0: 'sobre o dataset', 2: 'sobre o cliente', 3: 'bens do cliente', 4: 'pedido do emprestimo', 5: 'sobre a situacao profissional', 7: 'Informacoes sobre questoes sociais do cliente', 8: 'informacoes documentais', 9: 'consultas Externas sobre credito', 10: 'Alteracoes no registro', 11: 'fornecimento de informacoes de contato', 12: 'temporal', 13: 'confirmação de informação fornecida', 14: 'Dados externos', 15: 'Nivel social', 16: 'Caracteristicas do apto', 17: 'porao', 18: 'sem definicao', 19: 'tempo de construcao',20: 'area comum', 21: 'elevadores', 22: 'entradas', 23: 'tipo de cao', 25: 'terreno', 27: 'com sala', 28: 'sem sala', 30: 'construcao'})
df['tipo_grupo'] = df['tipo_grupo'].astype('category')
df['tipo_grupo'].value_counts()

In [0]:
# Transformar em pandas, dropar os NAs
dados = dados.toPandas()
dados= dados.dropna()

#tipar as variáveis

dados['NAME_CONTRACT_TYPE'] = dados['NAME_CONTRACT_TYPE'].astype('category')
dados['CODE_GENDER'] = dados['CODE_GENDER'].astype('category')
dados['FLAG_OWN_CAR'] = dados['FLAG_OWN_CAR'].astype('category')
dados['FLAG_OWN_REALTY'] = dados['FLAG_OWN_REALTY'].astype('category')
dados['NAME_TYPE_SUITE'] = dados['NAME_TYPE_SUITE'].astype('category')
dados['NAME_INCOME_TYPE'] = dados['NAME_INCOME_TYPE'].astype('category')
dados['NAME_EDUCATION_TYPE'] = dados['NAME_EDUCATION_TYPE'].astype('category')
dados['NAME_FAMILY_STATUS'] = dados['NAME_FAMILY_STATUS'].astype('category')
dados['NAME_HOUSING_TYPE'] = dados['NAME_HOUSING_TYPE'].astype('category')
dados['FLAG_EMP_PHONE'] = dados['FLAG_EMP_PHONE'].astype('category')
dados['FLAG_WORK_PHONE'] = dados['FLAG_WORK_PHONE'].astype('category')
dados['FLAG_PHONE'] = dados['FLAG_PHONE'].astype('category')
dados['FLAG_EMAIL'] = dados['FLAG_EMAIL'].astype('category')
dados['OCCUPATION_TYPE'] = dados['OCCUPATION_TYPE'].astype('category')
dados['CNT_FAM_MEMBERS'] = dados['CNT_FAM_MEMBERS'].astype('int32')
dados['REGION_RATING_CLIENT'] = dados['REGION_RATING_CLIENT'].astype('category')
dados['REGION_RATING_CLIENT_W_CITY'] = dados['REGION_RATING_CLIENT_W_CITY'].astype('category')
dados['WEEKDAY_APPR_PROCESS_START'] = dados['WEEKDAY_APPR_PROCESS_START'].astype('category')
dados['REG_REGION_NOT_LIVE_REGION'] = dados['REG_REGION_NOT_LIVE_REGION'].astype('category')
dados['REG_REGION_NOT_WORK_REGION'] = dados['REG_REGION_NOT_WORK_REGION'].astype('category')
dados['LIVE_REGION_NOT_WORK_REGION'] = dados['LIVE_REGION_NOT_WORK_REGION'].astype('category')
dados['REG_CITY_NOT_LIVE_CITY'] = dados['REG_CITY_NOT_LIVE_CITY'].astype('category')
dados['REG_CITY_NOT_WORK_CITY'] = dados['REG_CITY_NOT_WORK_CITY'].astype('category')
dados['LIVE_CITY_NOT_WORK_CITY'] = dados['LIVE_CITY_NOT_WORK_CITY'].astype('category')
dados['ORGANIZATION_TYPE'] = dados['ORGANIZATION_TYPE'].astype('category')
dados['FONDKAPREMONT_MODE'] = dados['FONDKAPREMONT_MODE'].astype('category')
dados['HOUSETYPE_MODE'] = dados['HOUSETYPE_MODE'].astype('category')
dados['WALLSMATERIAL_MODE'] = dados['WALLSMATERIAL_MODE'].astype('category')
dados['EMERGENCYSTATE_MODE'] = dados['EMERGENCYSTATE_MODE'].astype('category')
dados['DAYS_LAST_PHONE_CHANGE'] = dados['DAYS_LAST_PHONE_CHANGE'].astype('int32')
dados['OBS_30_CNT_SOCIAL_CIRCLE'] = dados['OBS_30_CNT_SOCIAL_CIRCLE'].astype('category')
dados['DEF_30_CNT_SOCIAL_CIRCLE'] = dados['DEF_30_CNT_SOCIAL_CIRCLE'].astype('category')
dados['OBS_60_CNT_SOCIAL_CIRCLE'] = dados['OBS_60_CNT_SOCIAL_CIRCLE'].astype('category')
dados['DEF_60_CNT_SOCIAL_CIRCLE'] = dados['DEF_60_CNT_SOCIAL_CIRCLE'].astype('category')
dados['DAYS_LAST_PHONE_CHANGE'] = dados['DAYS_LAST_PHONE_CHANGE'].astype('int32')
dados['FLAG_DOCUMENT_2'] = dados['FLAG_DOCUMENT_2'].astype('category')
dados['FLAG_DOCUMENT_3'] = dados['FLAG_DOCUMENT_3'].astype('category')
dados['FLAG_DOCUMENT_4'] = dados['FLAG_DOCUMENT_4'].astype('category')
dados['FLAG_DOCUMENT_5'] = dados['FLAG_DOCUMENT_5'].astype('category')
dados['FLAG_DOCUMENT_6'] = dados['FLAG_DOCUMENT_6'].astype('category')
dados['FLAG_DOCUMENT_7'] = dados['FLAG_DOCUMENT_7'].astype('category')
dados['FLAG_DOCUMENT_8'] = dados['FLAG_DOCUMENT_8'].astype('category')
dados['FLAG_DOCUMENT_9'] = dados['FLAG_DOCUMENT_9'].astype('category')
dados['FLAG_DOCUMENT_10'] = dados['FLAG_DOCUMENT_10'].astype('category')
dados['FLAG_DOCUMENT_11'] = dados['FLAG_DOCUMENT_11'].astype('category')
dados['FLAG_DOCUMENT_12'] = dados['FLAG_DOCUMENT_12'].astype('category')
dados['FLAG_DOCUMENT_13'] = dados['FLAG_DOCUMENT_13'].astype('category')
dados['FLAG_DOCUMENT_14'] = dados['FLAG_DOCUMENT_14'].astype('category')
dados['FLAG_DOCUMENT_15'] = dados['FLAG_DOCUMENT_15'].astype('category')
dados['FLAG_DOCUMENT_16'] = dados['FLAG_DOCUMENT_16'].astype('category')
dados['FLAG_DOCUMENT_17'] = dados['FLAG_DOCUMENT_17'].astype('category')
dados['FLAG_DOCUMENT_18'] = dados['FLAG_DOCUMENT_18'].astype('category')
dados['FLAG_DOCUMENT_19'] = dados['FLAG_DOCUMENT_19'].astype('category')
dados['FLAG_DOCUMENT_20'] = dados['FLAG_DOCUMENT_20'].astype('category')
dados['FLAG_DOCUMENT_21'] = dados['FLAG_DOCUMENT_21'].astype('category')
dados['AMT_REQ_CREDIT_BUREAU_HOUR'] = dados['AMT_REQ_CREDIT_BUREAU_HOUR'].astype('category')
dados['AMT_REQ_CREDIT_BUREAU_DAY'] = dados['AMT_REQ_CREDIT_BUREAU_DAY'].astype('category')
dados['AMT_REQ_CREDIT_BUREAU_WEEK'] = dados['AMT_REQ_CREDIT_BUREAU_WEEK'].astype('category')
dados['AMT_REQ_CREDIT_BUREAU_MON'] = dados['AMT_REQ_CREDIT_BUREAU_MON'].astype('category')
dados['AMT_REQ_CREDIT_BUREAU_QRT'] = dados['AMT_REQ_CREDIT_BUREAU_QRT'].astype('category')
dados['AMT_REQ_CREDIT_BUREAU_YEAR'] = dados['AMT_REQ_CREDIT_BUREAU_YEAR'].astype('category')
dados['FLAG_MOBIL'] = dados['FLAG_MOBIL'].astype('category')
dados['FLAG_CONT_MOBILE'] = dados['FLAG_CONT_MOBILE'].astype('category')
dados['SK_ID_CURR'] = dados['SK_ID_CURR'].astype('int32')

# Verificar o numero das tipagens
pd.set_option('display.max_rows', None)
tipos = dados.dtypes
tipos = pd.DataFrame(tipos, columns = ['feature'])
tipos['feature'] = tipos['feature'].astype('string') 
tipos['feature'].value_counts()

In [0]:
#Extrair as colunas das vaiáveis numéricas do tipo int e float e agrupálas nas variáveis numéricas
floats = list(dados.select_dtypes(include=['float64']).columns)
ints = list(dados.select_dtypes(include=['int32']).columns)
variaveis_numericas = floats + ints
variaveis_numericas = dados[variaveis_numericas]

#### Análise de Correlação e Colinearidade

In [0]:
# Plotando Correlação das variáveis
corr = variaveis_numericas.corr()
corr = corr.reset_index(level = 0)

In [0]:
# extraindo as correlações das preditoras em função da variável Target
juntar_compara = corr.rename(columns = {'index': 'feature'})
juntar_compara = juntar_compara[['feature', 'TARGET']]

In [0]:
#Extraindo o VIF para analise de colinearidade
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif_data = pd.DataFrame()
vif_data["feature"] = variaveis_numericas.columns
vif_data["VIF"] = [variance_inflation_factor(variaveis_numericas.values, i)
                          for i in range(len(variaveis_numericas.columns))]

In [0]:
# Unindo o valor do VIF e Correlação  com o dicionário de dados para analisar as variáveis
compara = pd.merge(df, vif_data, how = 'inner', on = 'feature')
compara = pd.merge(compara, juntar_compara, how = 'inner', on = 'feature')
compara = compara.rename(columns = {'TARGET': 'Correlacao'})

In [0]:
compara['group'].unique()

In [0]:
compara[compara['group'] == 2]
#DAYS_BIRTH

,_c0,Table,grupos,Tipo,feature,_c5,Description,Special,group,tipo_grupo,VIF,Correlacao
7,20,application_{train|test}.csv,None,None,DAYS_BIRTH,idade do cliente em dias no momento da inscri��o,Client's age in days at the time of application,time only relative to the application,2,sobre o cliente,31.79847,0.041108
12,32,application_{train|test}.csv,None,None,CNT_FAM_MEMBERS,quantidade de membros da familia,How many family members does client have,None,2,sobre o cliente,8.08930,-0.023435

In [0]:
compara[compara['group'] == 4]
#DAYS_BIRTH, AMT_INCOME_TOTAL

,_c0,Table,grupos,Tipo,feature,_c5,Description,Special,group,tipo_grupo,VIF,Correlacao
2,10,application_{train|test}.csv,None,None,AMT_INCOME_TOTAL,renda do cliente,Income of the client,None,4,pedido do emprestimo,4.569420,-0.039762
3,11,application_{train|test}.csv,None,None,AMT_CREDIT,Valor do emprestimo,Credit amount of the loan,None,4,pedido do emprestimo,140.190495,-0.014634
4,12,application_{train|test}.csv,None,None,AMT_ANNUITY,anuidade do emprestimo,Loan annuity,None,4,pedido do emprestimo,11.673314,-0.000765
5,13,application_{train|test}.csv,None,None,AMT_GOODS_PRICE,O valor do emprestimo concedido ao cliente � d...,For consumer loans it is the price of the good...,None,4,pedido do emprestimo,139.508251,-0.021950

In [0]:
compara[compara['group'] == 15]
# DAYS_BIRTH, AMT_INCOME_TOTAL, REGION_POPULATION_RELATIVE

,_c0,Table,grupos,Tipo,feature,_c5,Description,Special,group,tipo_grupo,VIF,Correlacao
6,19,application_{train|test}.csv,None,None,REGION_POPULATION_RELATIVE,None,Normalized population of region where client l...,normalized,15,Nivel social,4.432924,-0.021225

In [0]:
compara[compara['group'] == 3]
# DAYS_BIRTH, AMT_INCOME_TOTAL, REGION_POPULATION_RELATIVE, OWN_CAR_AGE

,_c0,Table,grupos,Tipo,feature,_c5,Description,Special,group,tipo_grupo,VIF,Correlacao
11,24,application_{train|test}.csv,None,None,OWN_CAR_AGE,ano do carro do cliente,Age of client's car,None,3,bens do cliente,1.884126,0.028052

In [0]:
compara[compara['group'] == 12]
# DAYS_BIRTH, AMT_INCOME_TOTAL, REGION_POPULATION_RELATIVE, OWN_CAR_AGE, HOUR_APPR_PROCESS_START

,_c0,Table,grupos,Tipo,feature,_c5,Description,Special,group,tipo_grupo,VIF,Correlacao
13,36,application_{train|test}.csv,None,None,HOUR_APPR_PROCESS_START,hora que o cliente aplicou o emprestimo,Approximately at what hour did the client appl...,rounded,12,temporal,15.688755,-0.013018

In [0]:
compara[compara['group'] == 14]
# DAYS_BIRTH, AMT_INCOME_TOTAL, REGION_POPULATION_RELATIVE, OWN_CAR_AGE, HOUR_APPR_PROCESS_START, EXT_SOURCE_3

,_c0,Table,grupos,Tipo,feature,_c5,Description,Special,group,tipo_grupo,VIF,Correlacao
14,44,application_{train|test}.csv,None,None,EXT_SOURCE_1,None,Normalized score from external data source,normalized,14,Dados externos,10.157661,-0.129548
15,45,application_{train|test}.csv,None,None,EXT_SOURCE_2,None,Normalized score from external data source,normalized,14,Dados externos,13.359104,-0.130969
16,46,application_{train|test}.csv,None,None,EXT_SOURCE_3,None,Normalized score from external data source,normalized,14,Dados externos,8.319007,-0.150720

In [0]:
compara[compara['group'] == 16]
# DAYS_BIRTH, AMT_INCOME_TOTAL, REGION_POPULATION_RELATIVE, OWN_CAR_AGE, HOUR_APPR_PROCESS_START, EXT_SOURCE_3, APARTMENTS_MODE

,_c0,Table,grupos,Tipo,feature,_c5,Description,Special,group,tipo_grupo,VIF,Correlacao
17,47,application_{train|test}.csv,None,None,APARTMENTS_AVG,None,Normalized information about building where th...,normalized,16,Caracteristicas do apto,684.874038,-0.028069
31,61,application_{train|test}.csv,None,None,APARTMENTS_MODE,None,Normalized information about building where th...,normalized,16,Caracteristicas do apto,142.890965,-0.022803
45,75,application_{train|test}.csv,None,None,APARTMENTS_MEDI,None,Normalized information about building where th...,normalized,16,Caracteristicas do apto,683.055991,-0.026566

In [0]:
compara[compara['group'] == 17]
# DAYS_BIRTH, AMT_INCOME_TOTAL, REGION_POPULATION_RELATIVE, OWN_CAR_AGE, HOUR_APPR_PROCESS_START, EXT_SOURCE_3, APARTMENTS_MODE, BASEMENTAREA_MODE

,_c0,Table,grupos,Tipo,feature,_c5,Description,Special,group,tipo_grupo,VIF,Correlacao
18,48,application_{train|test}.csv,None,None,BASEMENTAREA_AVG,None,Normalized information about building where th...,normalized,17,porao,129.572271,-0.018369
32,62,application_{train|test}.csv,None,None,BASEMENTAREA_MODE,None,Normalized information about building where th...,normalized,17,porao,74.831907,-0.011255
46,76,application_{train|test}.csv,None,None,BASEMENTAREA_MEDI,None,Normalized information about building where th...,normalized,17,porao,176.075857,-0.017046

In [0]:
compara[compara['group'] == 18]
# DAYS_BIRTH, AMT_INCOME_TOTAL, REGION_POPULATION_RELATIVE, OWN_CAR_AGE, HOUR_APPR_PROCESS_START, EXT_SOURCE_3, APARTMENTS_MODE, BASEMENTAREA_MODE, YEARS_BEGINEXPLUATATION_MEDI, YEARS_BUILD_MODE

,_c0,Table,grupos,Tipo,feature,_c5,Description,Special,group,tipo_grupo,VIF,Correlacao
19,49,application_{train|test}.csv,None,None,YEARS_BEGINEXPLUATATION_AVG,None,Normalized information about building where th...,normalized,18,sem definicao,105121.806106,-0.009067
33,63,application_{train|test}.csv,None,None,YEARS_BEGINEXPLUATATION_MODE,None,Normalized information about building where th...,normalized,18,sem definicao,9780.125024,-0.000480
47,77,application_{train|test}.csv,None,None,YEARS_BEGINEXPLUATATION_MEDI,None,Normalized information about building where th...,normalized,18,sem definicao,58815.411930,-0.012774

In [0]:
compara[compara['group'] == 19]
# DAYS_BIRTH, AMT_INCOME_TOTAL, REGION_POPULATION_RELATIVE, COMMONAREA_MODE, OWN_CAR_AGE, HOUR_APPR_PROCESS_START, EXT_SOURCE_3, APARTMENTS_MODE, BASEMENTAREA_MODE, YEARS_BEGINEXPLUATATION_MEDI, YEARS_BUILD_MODE

,_c0,Table,grupos,Tipo,feature,_c5,Description,Special,group,tipo_grupo,VIF,Correlacao
20,50,application_{train|test}.csv,None,None,YEARS_BUILD_AVG,None,Normalized information about building where th...,normalized,19,tempo de construcao,16294.841268,-0.026922
34,64,application_{train|test}.csv,None,None,YEARS_BUILD_MODE,None,Normalized information about building where th...,normalized,19,tempo de construcao,2822.829301,-0.025116
48,78,application_{train|test}.csv,None,None,YEARS_BUILD_MEDI,None,Normalized information about building where th...,normalized,19,tempo de construcao,16597.496101,-0.026491

In [0]:
compara[compara['group'] == 20]
# DAYS_BIRTH, AMT_INCOME_TOTAL, REGION_POPULATION_RELATIVE, OWN_CAR_AGE, HOUR_APPR_PROCESS_START, EXT_SOURCE_3, APARTMENTS_MODE, BASEMENTAREA_MODE, YEARS_BEGINEXPLUATATION_MEDI, YEARS_BUILD_MODE, COMMONAREA_MODE

,_c0,Table,grupos,Tipo,feature,_c5,Description,Special,group,tipo_grupo,VIF,Correlacao
21,51,application_{train|test}.csv,None,None,COMMONAREA_AVG,None,Normalized information about building where th...,normalized,20,area comum,279.106779,-0.013901
35,65,application_{train|test}.csv,None,None,COMMONAREA_MODE,None,Normalized information about building where th...,normalized,20,area comum,49.444716,-0.011093
49,79,application_{train|test}.csv,None,None,COMMONAREA_MEDI,None,Normalized information about building where th...,normalized,20,area comum,276.084150,-0.013755

In [0]:
compara[compara['group'] == 21]
# DAYS_BIRTH, AMT_INCOME_TOTAL, REGION_POPULATION_RELATIVE, OWN_CAR_AGE, HOUR_APPR_PROCESS_START, EXT_SOURCE_3, APARTMENTS_MODE, BASEMENTAREA_MODE, YEARS_BEGINEXPLUATATION_MEDI, YEARS_BUILD_MODE, COMMONAREA_MODE, ELEVATORS_MODE

,_c0,Table,grupos,Tipo,feature,_c5,Description,Special,group,tipo_grupo,VIF,Correlacao
22,52,application_{train|test}.csv,None,None,ELEVATORS_AVG,None,Normalized information about building where th...,normalized,21,elevadores,324.368216,-0.025762
36,66,application_{train|test}.csv,None,None,ELEVATORS_MODE,None,Normalized information about building where th...,normalized,21,elevadores,90.313228,-0.022441
50,80,application_{train|test}.csv,None,None,ELEVATORS_MEDI,None,Normalized information about building where th...,normalized,21,elevadores,389.309508,-0.024361

In [0]:
compara[compara['group'] == 22]
# DAYS_BIRTH, AMT_INCOME_TOTAL, REGION_POPULATION_RELATIVE, OWN_CAR_AGE, HOUR_APPR_PROCESS_START, EXT_SOURCE_3, APARTMENTS_MODE, BASEMENTAREA_MODE, YEARS_BEGINEXPLUATATION_MEDI, YEARS_BUILD_MODE, COMMONAREA_MODE, ELEVATORS_MODE, ENTRANCES_MODE

,_c0,Table,grupos,Tipo,feature,_c5,Description,Special,group,tipo_grupo,VIF,Correlacao
23,53,application_{train|test}.csv,None,None,ENTRANCES_AVG,None,Normalized information about building where th...,normalized,22,entradas,719.681128,-0.006426
37,67,application_{train|test}.csv,None,None,ENTRANCES_MODE,None,Normalized information about building where th...,normalized,22,entradas,150.535687,-0.005097
51,81,application_{train|test}.csv,None,None,ENTRANCES_MEDI,None,Normalized information about building where th...,normalized,22,entradas,826.865770,-0.005648

In [0]:
compara[compara['group'] == 23]
# DAYS_BIRTH, AMT_INCOME_TOTAL, REGION_POPULATION_RELATIVE, OWN_CAR_AGE, HOUR_APPR_PROCESS_START, EXT_SOURCE_3, APARTMENTS_MODE, BASEMENTAREA_MODE, YEARS_BEGINEXPLUATATION_MEDI, YEARS_BUILD_MODE, COMMONAREA_MODE, ELEVATORS_MODE, ENTRANCES_MODE, FLOORSMAX_MODE

,_c0,Table,grupos,Tipo,feature,_c5,Description,Special,group,tipo_grupo,VIF,Correlacao
24,54,application_{train|test}.csv,None,None,FLOORSMAX_AVG,None,Normalized information about building where th...,normalized,23,tipo de cao,879.241826,-0.046110
25,55,application_{train|test}.csv,None,None,FLOORSMIN_AVG,None,Normalized information about building where th...,normalized,23,tipo de cao,620.688380,-0.032904
38,68,application_{train|test}.csv,None,None,FLOORSMAX_MODE,None,Normalized information about building where th...,normalized,23,tipo de cao,216.007234,-0.045990
39,69,application_{train|test}.csv,None,None,FLOORSMIN_MODE,None,Normalized information about building where th...,normalized,23,tipo de cao,206.831722,-0.031688
52,82,application_{train|test}.csv,None,None,FLOORSMAX_MEDI,None,Normalized information about building where th...,normalized,23,tipo de cao,1011.921717,-0.045206
53,83,application_{train|test}.csv,None,None,FLOORSMIN_MEDI,None,Normalized information about building where th...,normalized,23,tipo de cao,768.932752,-0.033313

In [0]:
compara[compara['group'] == 25]
# DAYS_BIRTH, AMT_INCOME_TOTAL, REGION_POPULATION_RELATIVE, OWN_CAR_AGE, HOUR_APPR_PROCESS_START, EXT_SOURCE_3, APARTMENTS_MODE, BASEMENTAREA_MODE, YEARS_BEGINEXPLUATATION_MEDI, YEARS_BUILD_MODE, COMMONAREA_MODE, ELEVATORS_MODE, ENTRANCES_MODE, FLOORSMAX_MODE, LANDAREA_AVG

,_c0,Table,grupos,Tipo,feature,_c5,Description,Special,group,tipo_grupo,VIF,Correlacao
26,56,application_{train|test}.csv,None,None,LANDAREA_AVG,None,Normalized information about building where th...,normalized,25,terreno,85.649383,-0.007582
40,70,application_{train|test}.csv,None,None,LANDAREA_MODE,None,Normalized information about building where th...,normalized,25,terreno,56.581301,-0.005889
54,84,application_{train|test}.csv,None,None,LANDAREA_MEDI,None,Normalized information about building where th...,normalized,25,terreno,138.810387,-0.007566

In [0]:
compara[compara['group'] == 27]
# DAYS_BIRTH, AMT_INCOME_TOTAL, REGION_POPULATION_RELATIVE, OWN_CAR_AGE, HOUR_APPR_PROCESS_START, EXT_SOURCE_3, APARTMENTS_MODE, BASEMENTAREA_MODE, YEARS_BEGINEXPLUATATION_MEDI, YEARS_BUILD_MODE, COMMONAREA_MODE, ELEVATORS_MODE, ENTRANCES_MODE, FLOORSMAX_MODE, LANDAREA_AVG, LIVINGAPARTMENTS_MODE

,_c0,Table,grupos,Tipo,feature,_c5,Description,Special,group,tipo_grupo,VIF,Correlacao
27,57,application_{train|test}.csv,None,None,LIVINGAPARTMENTS_AVG,None,Normalized information about building where th...,normalized,27,com sala,471.743084,-0.028103
28,58,application_{train|test}.csv,None,None,LIVINGAREA_AVG,None,Normalized information about building where th...,normalized,27,com sala,960.987742,-0.025545
41,71,application_{train|test}.csv,None,None,LIVINGAPARTMENTS_MODE,None,Normalized information about building where th...,normalized,27,com sala,80.077578,-0.024423
42,72,application_{train|test}.csv,None,None,LIVINGAREA_MODE,None,Normalized information about building where th...,normalized,27,com sala,105.592060,-0.024207
55,85,application_{train|test}.csv,None,None,LIVINGAPARTMENTS_MEDI,None,Normalized information about building where th...,normalized,27,com sala,516.501518,-0.026595
56,86,application_{train|test}.csv,None,None,LIVINGAREA_MEDI,None,Normalized information about building where th...,normalized,27,com sala,874.292539,-0.024612

In [0]:
compara[compara['group'] == 28]
# DAYS_BIRTH, AMT_INCOME_TOTAL, REGION_POPULATION_RELATIVE, OWN_CAR_AGE, HOUR_APPR_PROCESS_START, EXT_SOURCE_3, APARTMENTS_MODE, BASEMENTAREA_MODE, YEARS_BEGINEXPLUATATION_MEDI, YEARS_BUILD_MODE, COMMONAREA_MODE, ELEVATORS_MODE, ENTRANCES_MODE, FLOORSMAX_MODE, LANDAREA_AVG, LIVINGAPARTMENTS_MODE, NONLIVINGAREA_AVG

,_c0,Table,grupos,Tipo,feature,_c5,Description,Special,group,tipo_grupo,VIF,Correlacao
29,59,application_{train|test}.csv,None,None,NONLIVINGAPARTMENTS_AVG,None,Normalized information about building where th...,normalized,28,sem sala,93.447698,0.009610
30,60,application_{train|test}.csv,None,None,NONLIVINGAREA_AVG,None,Normalized information about building where th...,normalized,28,sem sala,33.059998,-0.023182
43,73,application_{train|test}.csv,None,None,NONLIVINGAPARTMENTS_MODE,None,Normalized information about building where th...,normalized,28,sem sala,32.293221,0.013384
44,74,application_{train|test}.csv,None,None,NONLIVINGAREA_MODE,None,Normalized information about building where th...,normalized,28,sem sala,17.496514,-0.018975
57,87,application_{train|test}.csv,None,None,NONLIVINGAPARTMENTS_MEDI,None,Normalized information about building where th...,normalized,28,sem sala,124.641273,0.011152
58,88,application_{train|test}.csv,None,None,NONLIVINGAREA_MEDI,None,Normalized information about building where th...,normalized,28,sem sala,45.586333,-0.022205

In [0]:
compara[compara['group'] == 30]
# DAYS_BIRTH, AMT_INCOME_TOTAL, REGION_POPULATION_RELATIVE, OWN_CAR_AGE, HOUR_APPR_PROCESS_START, EXT_SOURCE_3, APARTMENTS_MODE, BASEMENTAREA_MODE, YEARS_BEGINEXPLUATATION_MEDI, YEARS_BUILD_MODE, COMMONAREA_MODE, ELEVATORS_MODE, ENTRANCES_MODE, FLOORSMAX_MODE, LANDAREA_AVG, LIVINGAPARTMENTS_MODE, NONLIVINGAREA_AVG, TOTALAREA_MODE

,_c0,Table,grupos,Tipo,feature,_c5,Description,Special,group,tipo_grupo,VIF,Correlacao
59,91,application_{train|test}.csv,None,None,TOTALAREA_MODE,None,Normalized information about building where th...,normalized,30,construcao,18.73407,-0.029714

#### Seleção das melhores preditoras e separação da variável target

In [0]:
variaveis_numericas_copy = dados[['DAYS_BIRTH', 'AMT_INCOME_TOTAL', 'REGION_POPULATION_RELATIVE', 'OWN_CAR_AGE', 'HOUR_APPR_PROCESS_START', 'EXT_SOURCE_3', 'APARTMENTS_MODE', 'BASEMENTAREA_MODE', 'YEARS_BEGINEXPLUATATION_MEDI', 'YEARS_BUILD_MODE', 'COMMONAREA_MODE', 'ELEVATORS_MODE', 'ENTRANCES_MODE', 'FLOORSMAX_MODE', 'LANDAREA_AVG', 'LIVINGAPARTMENTS_MODE', 'NONLIVINGAREA_AVG', 'TOTALAREA_MODE']]
categoricas = dados.select_dtypes('category')
var = dados.drop(variaveis_numericas_copy, axis = 1)
var = var.drop(categoricas,axis = 1)
variaveis_numericas_copy = dados.drop(var, axis = 1)
X = pd.DataFrame(variaveis_numericas_copy)
y = dados['TARGET']

In [0]:
display(X)

# Methods

### selecao_RFC

#### Documentação
---
https://adb-6226397775262915.15.azuredatabricks.net/?o=6226397775262915#notebook/1121831065220354/command/3749511783432582

#### Exemplo

In [0]:
preditoras = selecao_RFC(X,y, 85)

##### Análise pós Modelo

In [0]:
#unindo valiáveis preditoras com a variável target
target = y.to_frame(name='Target')
target['key'] = [i + 1 for i in  range(0, len(target))]
preditoras = preditoras.toPandas()
categoricas = preditoras.select_dtypes('object')
numericas = preditoras.drop(categoricas, axis = 1)
numericas['key'] = [i + 1 for i in range(0, len(numericas))]
gogo = numericas.set_index('key').join(target.set_index('key'), on = 'key')

# verificando a multicolinearidade
vif_data1 = pd.DataFrame()
vif_data1["feature"] = gogo.columns
vif_data1["VIF"] = [variance_inflation_factor(gogo.values, i)
                          for i in range(len(gogo.columns))]
comp = pd.merge(vif_data1, vif_data, how = 'outer', on = 'feature')
comp = pd.merge(comp, juntar_compara, how = 'outer', on = 'feature')

# criando correlação do modelo
corr_modelo = gogo.corr()
corr_modelo = corr_modelo.reset_index(level = 0)
corr_modelo = corr_modelo.rename(columns = {'index': 'feature'})
corr_modelo = corr_modelo[['feature', 'Target']]

#merge correlação do modelo à tabela de comparação
comp = pd.merge(comp, corr_modelo, how = 'inner', on = 'feature')
comp = comp.rename(columns = {'VIF_x': 'VIF_Modelo', 'VIF_y': 'VIF_dataframe', 'TARGET': 'Correlação_dataframe', 'Target': 'Correlação_Modelo'})
display(comp)

feature,VIF_Modelo,VIF_dataframe,Correlação_dataframe,Correlação_Modelo
EXT_SOURCE_3,8.00418518170467,8.319007404508849,-0.15072007728486228,-0.15072007728486228
DAYS_BIRTH,20.772146847969914,31.7984700729185,0.04110775777658233,0.04110775777658235
TOTALAREA_MODE,9.01943796951053,18.734069658867092,-0.029713532258079538,-0.02971353225807953
LANDAREA_AVG,2.175753298625805,85.6493830540056,-0.007581792139074115,-0.007581792139074115
COMMONAREA_MODE,2.0588225647613876,49.444716437794106,-0.011093058554813632,-0.01109305855481363
BASEMENTAREA_MODE,4.141053512516692,74.83190703443923,-0.011254977709792335,-0.011254977709792334
LIVINGAPARTMENTS_MODE,20.13813390292905,80.07757831366838,-0.024422577404566763,-0.024422577404566763
YEARS_BUILD_MODE,69.55249886941749,2822.829300799926,-0.025115857864893353,-0.025115857864893367
OWN_CAR_AGE,1.8630576361537583,1.8841263189883735,0.02805236861394144,0.028052368613941437
REGION_POPULATION_RELATIVE,3.4927846535381297,4.432924467430049,-0.021225391125633663,-0.021225391125633663
APARTMENTS_MODE,23.775067286219237,142.89096488627266,-0.02280253258482067,-0.022802532584820682
YEARS_BEGINEXPLUATATION_MEDI,97.86678410319347,58815.41193043053,-0.012773881158726335,-0.012773881158726321
AMT_INCOME_TOTAL,3.799196797805635,4.569420202633934,-0.03976162549322639,-0.039761625493226385
Target,1.0941057845990667,null,null,1.0

### selecao_ETC

#### Documentação
---
https://adb-6226397775262915.15.azuredatabricks.net/?o=6226397775262915#notebook/1121831065220354/command/3749511783432583

#### Exemplo

In [0]:
preditoras2 = selecao_etc(X,y,60.3)

In [0]:
display(preditoras2)

##### Análise pós Modelo

In [0]:
#unindo valiáveis preditoras com a variável target
target2 = y.to_frame(name='Target2')
target2['key'] = [i + 1 for i in  range(0, len(target2))]
preditoras2 = preditoras2.toPandas()
categoricas2 = preditoras2.select_dtypes('object')
numericas2 = preditoras2.drop(categoricas2, axis = 1)
numericas2['key'] = [i + 1 for i in range(0, len(numericas2))]
gogo2 = numericas2.set_index('key').join(target2.set_index('key'), on = 'key')

# verificando a multicolinearidade
vif_data2 = pd.DataFrame()
vif_data2["feature"] = gogo2.columns
vif_data2["VIF"] = [variance_inflation_factor(gogo2.values, i)
                          for i in range(len(gogo2.columns))]
comp2 = pd.merge(vif_data2, vif_data, how = 'outer', on = 'feature')
comp2 = pd.merge(comp2, juntar_compara, how = 'outer', on = 'feature')

# criando correlação do modelo
corr_modelo2 = gogo2.corr()
corr_modelo2 = corr_modelo2.reset_index(level = 0)
corr_modelo2 = corr_modelo2.rename(columns = {'index': 'feature'})
corr_modelo2 = corr_modelo2[['feature', 'Target2']]

#merge correlação do modelo à tabela de comparação
comp2 = pd.merge(comp2, corr_modelo2, how = 'inner', on = 'feature')
comp2 = comp2.rename(columns = {'VIF_x': 'VIF_Modelo', 'VIF_y': 'VIF_dataframe', 'TARGET': 'Correlação_dataframe', 'Target2': 'Correlação_Modelo'})
display(comp2)

feature,VIF_Modelo,VIF_dataframe,Correlação_dataframe,Correlação_Modelo
EXT_SOURCE_3,7.034882350997633,8.319007404508849,-0.15072007728486228,-0.15072007728486228
DAYS_BIRTH,12.419039106667377,31.7984700729185,0.04110775777658233,0.04110775777658235
OWN_CAR_AGE,1.7563901217301205,1.8841263189883735,0.02805236861394144,0.028052368613941437
COMMONAREA_MODE,2.0001953465986024,49.444716437794106,-0.011093058554813632,-0.01109305855481363
TOTALAREA_MODE,4.338117390941862,18.734069658867092,-0.029713532258079538,-0.02971353225807953
HOUR_APPR_PROCESS_START,10.17320472967896,15.688754892062464,-0.01301819702793722,-0.013018197027937226
LANDAREA_AVG,2.1369443124045766,85.6493830540056,-0.007581792139074115,-0.007581792139074115
BASEMENTAREA_MODE,3.7438807386482167,74.83190703443923,-0.011254977709792335,-0.011254977709792334
REGION_POPULATION_RELATIVE,3.426640523740263,4.432924467430049,-0.021225391125633663,-0.021225391125633663
Target2,1.076377638600367,null,null,1.0